on:
  pull_request:
    branches:
    - main
    types:
    - closed
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Extract First Label
      id: extract-label
      run: |
        $Labels = Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json | Select-Object -ExpandProperty pull_request | Select-Object -ExpandProperty labels
        $FirstLabel = $Labels[0].name
        Write-Host "First Label: $FirstLabel"
        echo "FIRST_LABEL=$FirstLabel" >> $ENV:GITHUB_OUTPUT

    - name: Use First Label
      run: |
        $FirstLabel = "${{ steps.extract-label.outputs.FIRST_LABEL }}"
        Write-Host "Using First Label: $FirstLabel"
        # Add your subsequent steps here using $FirstLabel
        
    - name: Run PowerShell Script
      shell: pwsh
      run: |
          cd ${{ github.workspace }}
          .\test.ps1 -inputValue "${{ steps.extract-label.outputs.FIRST_LABEL }}"
          
