on:
  pull_request:
    branches:
    - main
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-2019
    
    steps:
      - name: PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9
        
      - name: Get contents of files
        shell: pwsh
        run: Write-Host "${{ steps.pr-labels.outputs.labels }}"

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          pwd
          cd ..
          cat test.ps1
          ls
          cd ${{ github.workspace }}
          ls
          # .\test.ps1 -inputValue "${{ steps.pr-labels.outputs.labels }}"
